services:
  - type: web
    name: laravel-backend
    env: php
    buildCommand: "composer install"
    startCommand: "php artisan serve --host 0.0.0.0 --port 10000"
    envVars:
      - key: APP_KEY
        value: base64:uO7/e4DHDiYNSJlQIbFpv2Z9pYb2xk4UMc/r/tN/y8E=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        # value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: easy_nikah
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 12345678